[DO-1957] Add multiply citizenship countries
3v-workspace/DataOcean pull request #139
Opened 2021-06-11 09:05 UTC by Iva-khar

For multiply countries like:
![Screenshot from 2021-06-11 12-04-53](https://user-images.githubusercontent.com/60961669/121661828-4b839680-caad-11eb-9b14-1f359b0e7381.png)

2021-06-14 05:51 UTC, roman-tiukh requested changes

2021-06-14 05:51 UTC, roman-tiukh commented on src/components/pages/datasets/sanctions/PersonSanctionList.jsx
> +      render: (v) => getCountries(v),
```suggestion
      render: (countries) => countries.map((country) => country[`name_${i18n.language}`]).join(', '),
```

2021-06-14 11:35 UTC, Iva-khar commented on src/components/pages/datasets/sanctions/PersonSanctionList.jsx
> +      render: (v) => getCountries(v),
Thanks. Done.

2021-06-15 07:42 UTC, roman-tiukh approved these changes

2021-06-15 07:42 UTC, merged