[DO-1969] Reset filters button
3v-workspace/DataOcean pull request #171
Opened 2021-08-03 18:46 UTC by Iva-khar

2021-08-04 07:12 UTC, roman-tiukh requested changes

2021-08-04 07:12 UTC, roman-tiukh commented on src/components/table/Table.jsx
> +      </div>
what if there are no filters?

2021-08-04 13:58 UTC, Iva-khar commented on src/components/table/Table.jsx
> +      </div>
Added hiding if no filters

2021-08-05 05:14 UTC, roman-tiukh approved these changes

2021-08-05 08:53 UTC, merged