Upd of sanctions pages
3v-workspace/DataOcean pull request #199
Opened 2021-09-06 09:17 UTC by Andrii17s

Внести змінм в загальний вигляд сторінки відповідно до зразку
https://www.figma.com/file/ZsbdiuhEmsykHPNILBu3Qp/Sanctions?node-id=525%3A2

2021-09-06 10:50 UTC, AlenaYanish approved these changes

2021-09-07 07:05 UTC, roman-tiukh requested changes

2021-09-07 07:05 UTC, roman-tiukh commented on src/locales/uk/translation.json
> +  "companyName": "Назва",
nope

2021-09-07 07:05 UTC, roman-tiukh commented on src/locales/uk/translation.json
> +      "q15": "Для наповнення Реєстру  використано інформацію, що отримана в рамках реалізації ГО «Центр протидії корупції» свого права на доступ до публічної інформації, а також інформацію з відкрити
extra space

2021-09-07 07:05 UTC, roman-tiukh commented on src/locales/uk/translation.json
> +  "taxpayerNumberCompany": "Номер платника податків",
what different? I think we can merge his at one

2021-09-07 07:07 UTC, roman-tiukh requested changes
pls... use i18n editor
https://github.com/jcbvm/i18n-editor

2021-09-08 06:30 UTC, roman-tiukh commented on src/locales/en/translation.json
> +  "companyNameInTable": "Company name",
what difference?

2021-09-08 06:30 UTC, roman-tiukh commented on src/locales/uk/translation.json
> +  "companyInfo": "Інформація про компанію",
?

2021-09-09 06:04 UTC, roman-tiukh approved these changes

2021-09-09 06:04 UTC, merged