[DO-1989] Preloader
3v-workspace/DataOcean pull request #203
Opened 2021-09-14 10:00 UTC by Iva-khar

2021-09-14 10:43 UTC, roman-tiukh requested changes

2021-09-14 10:43 UTC, roman-tiukh commented on public/index.html
> +      (function( w ){
this script should be moved to js file

2021-09-14 10:43 UTC, roman-tiukh commented on public/index.html
> +      window.onload = (() => {
use addEventListener

2021-09-14 15:29 UTC, Iva-khar commented on public/index.html
> +      window.onload = (() => {
done

2021-09-14 15:40 UTC, Iva-khar commented on public/index.html
> +      (function( w ){
done

2021-09-15 07:46 UTC, roman-tiukh approved these changes

2021-09-15 07:46 UTC, merged