[DO-2631]Add explanation for the type of PEP in PEP Detailed view page
3v-workspace/DataOcean pull request #252
Opened 2021-11-02 16:16 UTC by rpersten

2021-11-03 07:01 UTC, roman-tiukh requested changes

2021-11-03 14:07 UTC, rpersten commented on src/components/pages/datasets/pep/PepDetail.jsx
> +  const checkPEpType = tooltipList.find((item) => item.value === pep.pep_type);
Done

2021-11-03 14:08 UTC, rpersten commented on src/locales/en/translation.json
> +  "t5ForeignPEp": "We don't need explanation yet.",
Done

2021-11-03 14:08 UTC, rpersten commented on src/components/pages/datasets/pep/PepDetail.jsx
> +          {checkPEpType.label && (
Done

2021-11-04 12:18 UTC, roman-tiukh approved these changes

2021-11-04 12:18 UTC, merged