[DO-2613]Rename "back" to on PEP detailed view page.
3v-workspace/DataOcean pull request #253
Opened 2021-11-04 15:13 UTC by rpersten

…ew page

2021-11-04 15:17 UTC, roman-tiukh requested changes

2021-11-04 15:17 UTC, roman-tiukh commented on src/components/pages/datasets/pep/PepDetail.jsx
> +import faqs from 'components/pages/help/faqs';
unused import

2021-11-04 15:17 UTC, roman-tiukh commented on src/components/pages/datasets/pep/PepDetail.jsx
> +          <div className="max-w-xl"><a href="/system/help/">{pep.pep_type_display}</a></div>
use react-router Link component

2021-11-04 15:20 UTC, rpersten commented on src/components/pages/datasets/pep/PepDetail.jsx
> +import faqs from 'components/pages/help/faqs';
Done

2021-11-04 15:20 UTC, rpersten commented on src/components/pages/datasets/pep/PepDetail.jsx
> +          <div className="max-w-xl"><a href="/system/help/">{pep.pep_type_display}</a></div>
Done

2021-11-23 07:59 UTC, roman-tiukh approved these changes

2021-11-23 07:59 UTC, merged