DO-630 and fix bug in link to DataPlatform
3v-workspace/DataOcean pull request #39
Opened 2020-11-19 15:01 UTC by AlenaYanish

2020-11-19 15:26 UTC, roman-tiukh requested changes

2020-11-19 15:26 UTC, roman-tiukh commented on landing/static/js/index.js
> +        url: "https://dataocean-ipa.ml/api/landing_mail/",
host should be a environment variable, for test its have one value for prod other.

2020-11-19 15:26 UTC, roman-tiukh commented on landing/static/js/index.js
> +                alert('Now you will be able to keep up with all of DataOcean updates!');
create a collection with messages, as I told you)

2020-11-19 19:26 UTC, roman-tiukh requested changes

2020-11-19 19:26 UTC, roman-tiukh commented on landing/static/js/index.js
> +                }
translations here

2020-11-19 19:26 UTC, roman-tiukh commented on landing/static/js/index.js
> +        url: "https://dataocean-ipa.ml/api/landing_mail/",
this is actual problem, you can change to https://ipa.dataocean.us temporary

2020-11-19 20:24 UTC, roman-tiukh requested changes

2020-11-19 20:24 UTC, roman-tiukh commented on landing/static/js/index.js
> +        url: "https://ipa.dataocean.us",
@AlenaYanish ......

2020-11-19 20:24 UTC, roman-tiukh commented on landing/static/js/index.js
> +                $('#question')[0].placeholder = t('placeholderQuestion');
this should located in other place

2020-11-19 20:24 UTC, roman-tiukh commented on landing/static/js/index.js
> +         return $(this).parents
what is $(this).parents

2020-11-24 14:31 UTC, roman-tiukh requested changes

2020-11-24 14:31 UTC, roman-tiukh commented on landing/static/js/index.js
> +        url: "process.env.PLATFORM_HOST",
... wrong link

2020-11-24 14:31 UTC, roman-tiukh commented on landing/.env.example
> +DO_BACKEND_HOST, DO_FRONTEND_HOST
```suggestion
DO_BACKEND_HOST=https://ipa.dataocean.us
DO_FRONTEND_HOST=https://dp.dataocean.us
```

2020-11-24 14:31 UTC, roman-tiukh commented on landing/.gitignore
> +/.env
```suggestion
/.env

```

2020-11-24 14:50 UTC, AlenaYanish commented on landing/static/js/index.js
> +        url: "process.env.PLATFORM_HOST",
I fix it in "add env vars" commit

2020-11-24 14:58 UTC, roman-tiukh approved these changes

2020-11-24 14:59 UTC, merged