Added api button and api page
3v-workspace/DataOcean pull request #69
Opened 2021-01-20 16:08 UTC by EmmaSamoilova

2021-01-21 07:03 UTC, roman-tiukh requested changes

2021-01-21 07:03 UTC, roman-tiukh commented on src/components/pages/api/ApiPage.jsx
> +                  >
add a transition to project view

2021-01-21 07:03 UTC, roman-tiukh commented on src/locales/en/translation.json
> +  "viewApiDocumentation": "View documentation",
maybe:
```suggestion
  "viewApiDocumentation": "View API documentation",
```
if key is "viewApiDocumentation"

2021-01-21 07:03 UTC, roman-tiukh commented on src/locales/uk/translation.json
> +  "viewApiDocumentation": "Переглянути документацію",
maybe
```suggestion
  "viewApiDocumentation": "Переглянути API-документацію",
```

2021-01-21 08:07 UTC, EmmaSamoilova commented on src/components/pages/api/ApiPage.jsx
> +          <p>atque omnis perferendis illo expedita doloremque accusamus</p>
Did like this https://www.figma.com/file/xYl9AHCL7BVesH3RJ2cU9f/API-left-menu?node-id=156%3A144

2021-01-21 08:11 UTC, roman-tiukh commented on src/components/pages/api/ApiPage.jsx
> +          <p>atque omnis perferendis illo expedita doloremque accusamus</p>
I'm sure this text shouldn't be here. Its just example.
You need to know what text will be placed here

2021-01-21 08:12 UTC, roman-tiukh commented on src/components/pages/api/ApiPage.jsx
> +          <p>atque omnis perferendis illo expedita doloremque accusamus</p>
https://ru.wikipedia.org/wiki/Lorem_ipsum

2021-01-22 07:25 UTC, roman-tiukh requested changes

2021-01-22 07:25 UTC, roman-tiukh commented on src/components/pages/api/ApiPage.jsx
> +                  <td onClick={() => history.push(`${projectUrl}${project.id}/`)}>{getProjectStatus(project)}</td>
onClick in `tr`?

2021-01-22 07:25 UTC, roman-tiukh commented on src/components/pages/api/ApiPage.jsx
> +  const projectUrl = `${match.url.replace('api/', '')}profile/projects/`;
You dont need this.
Just write /system/profile/projects/ in onClick function

2021-01-25 07:08 UTC, roman-tiukh approved these changes

2021-01-25 07:08 UTC, merged