DO-956 in footer "©2020 – Data Ocean. Всі права захищені."
3v-workspace/DataOcean pull request #90
Opened 2021-02-09 11:00 UTC by Litsyshyn

Added "All rights reserved" text to platform footer.

https://razom.atlassian.net/browse/DO-956

2021-02-09 13:36 UTC, roman-tiukh requested changes
bad positioning

2021-02-09 13:36 UTC, roman-tiukh commented on src/components/pages/auth/LoginPage.jsx
> +          </div>
![image](https://user-images.githubusercontent.com/38906004/107370699-fda15680-6aeb-11eb-9e8a-a8143d895a8f.png)

2021-02-09 13:36 UTC, roman-tiukh commented on src/components/pages/SystemPage.jsx
> +      </div>
![image](https://user-images.githubusercontent.com/38906004/107371021-6be61900-6aec-11eb-84ae-ecfcc1b3c910.png)

2021-02-11 08:25 UTC, Litsyshyn commented
I hope it looks better )

2021-02-11 13:16 UTC, roman-tiukh requested changes

2021-02-11 13:16 UTC, roman-tiukh commented on src/components/pages/auth/LoginPage.jsx
> +        <div className="grid grid-rows-100 gap-90 h-screen xl:h-auto flex py-5 xl:py-0 my-10 xl:my-0 relative">
```suggestion
        <div className="h-screen xl:h-auto flex flex-col py-5 xl:py-0 my-10 xl:my-0">
```

2021-02-11 13:16 UTC, roman-tiukh commented on src/components/pages/auth/LoginPage.jsx
> +          </div>
```suggestion
          <div className="mx-auto mb-8 xl:ml-20 text-white xl:text-gray-700">
            ©2020-2021 – Data Ocean. {t('allRightsReserved')}.
          </div>
```

2021-02-11 13:16 UTC, roman-tiukh commented on src/components/pages/SystemPage.jsx
> +      </div>
```suggestion
      <div className="flex justify-center items-center mt-3 xl:ml-64 lg:ml-32 md:ml-24 text-white">
        ©2020-2021 – Data Ocean. {t('allRightsReserved')}.
      </div>
```

2021-02-11 13:54 UTC, roman-tiukh approved these changes

2021-02-11 13:54 UTC, merged