[DO-1277] Implement Design of Button
3v-workspace/DataOcean pull request #95
Opened 2021-02-14 22:09 UTC by Andrii17s

Implemented

2021-02-15 07:07 UTC, roman-tiukh requested changes

2021-02-15 23:13 UTC, Andrii17s commented on src/components/pages/payment/ProjectDetail.jsx
> +  const ifDeleteUser = (user) => {
![Opera Snapshot_2021-02-16_011043_localhost](https://user-images.githubusercontent.com/75915283/108001025-0adea980-6ff4-11eb-97d2-ba500c4fb6f3.png)

2021-02-16 12:47 UTC, roman-tiukh requested changes

2021-02-16 12:47 UTC, roman-tiukh commented on src/components/pages/payment/ProjectDetail.jsx
> +        $.toast(t('userDeleted'));
toasts was reworked

2021-02-16 12:47 UTC, roman-tiukh commented on src/components/pages/payment/ProjectDetail.jsx
> +          icon={X}
no need this prop

2021-02-17 07:48 UTC, roman-tiukh approved these changes

2021-02-17 12:59 UTC, roman-tiukh approved these changes

2021-02-17 13:00 UTC, merged